/** EventUs — temas 360° por comunidad (sincronizado con backend/config/communityThemes.js) */
export const COMMUNITY_THEMES = {
  voluntariado: {
    slug: 'voluntariado',
    name: 'Voluntariado',
    tagline: 'Manos que construyen impacto',
    icon: 'hand-left-outline',
    colors: {
      primary: '#6BCB77',
      primary_container: '#2D5A3D',
      on_primary: '#0A1F12',
      secondary: '#A8E6CF',
      accent: '#FFD93D',
      surface: '#0D1410',
      surface_container_high: '#1A2B1F',
      surface_container_highest: '#243528',
      on_surface: '#E8F5E9',
      outline: '#5A7A62',
      live: '#6BCB77',
      live_bg: 'rgba(107, 203, 119, 0.18)',
    },
    gradient: ['#0D1410', '#1A3D28', '#6BCB77'],
  },
  benefico: {
    slug: 'benefico',
    name: 'Benéfico',
    tagline: 'Cada gesto suma',
    icon: 'heart-outline',
    colors: {
      primary: '#FF8A80',
      primary_container: '#5C2E2A',
      on_primary: '#2A0F0D',
      secondary: '#FFCCBC',
      accent: '#FFD54F',
      surface: '#140E0D',
      surface_container_high: '#2A1A18',
      surface_container_highest: '#3D2622',
      on_surface: '#FFF3F0',
      outline: '#8A6A65',
      live: '#FF5252',
      live_bg: 'rgba(255, 82, 82, 0.15)',
    },
    gradient: ['#140E0D', '#3D1F1A', '#FF8A80'],
  },
  quedada: {
    slug: 'quedada',
    name: 'Quedada',
    tagline: 'Nunca vayas solo',
    icon: 'people-outline',
    colors: {
      primary: '#FF6B6B',
      primary_container: '#4A2525',
      on_primary: '#1F0A0A',
      secondary: '#FFB4A2',
      accent: '#4ECDC4',
      surface: '#120C0C',
      surface_container_high: '#221818',
      surface_container_highest: '#322424',
      on_surface: '#FFF0EE',
      outline: '#8A6560',
      live: '#FF6B6B',
      live_bg: 'rgba(255, 107, 107, 0.2)',
    },
    gradient: ['#120C0C', '#3D2020', '#FF6B6B'],
  },
  reunion: {
    slug: 'reunion',
    name: 'Reunión',
    tagline: 'Encuentros con propósito',
    icon: 'briefcase-outline',
    colors: {
      primary: '#64B5F6',
      primary_container: '#1E3A5F',
      on_primary: '#0A1520',
      secondary: '#90CAF9',
      accent: '#81C784',
      surface: '#0A0E14',
      surface_container_high: '#141C28',
      surface_container_highest: '#1E2A3D',
      on_surface: '#E3F2FD',
      outline: '#5A7088',
      live: '#42A5F5',
      live_bg: 'rgba(66, 165, 245, 0.18)',
    },
    gradient: ['#0A0E14', '#1E3A5F', '#64B5F6'],
  },
  concierto: {
    slug: 'concierto',
    name: 'Concierto',
    tagline: 'Vive la música juntos',
    icon: 'musical-notes-outline',
    colors: {
      primary: '#CE93D8',
      primary_container: '#4A2C5C',
      on_primary: '#1A0A22',
      secondary: '#E1BEE7',
      accent: '#FF4081',
      surface: '#0C0810',
      surface_container_high: '#1A1224',
      surface_container_highest: '#2A1C38',
      on_surface: '#F3E5F5',
      outline: '#7A6088',
      live: '#E040FB',
      live_bg: 'rgba(224, 64, 251, 0.2)',
    },
    gradient: ['#0C0810', '#2A1040', '#CE93D8'],
  },
  deporte: {
    slug: 'deporte',
    name: 'Deporte',
    tagline: 'Muévete en comunidad',
    icon: 'football-outline',
    colors: {
      primary: '#FFB74D',
      primary_container: '#5C3D1A',
      on_primary: '#1F1408',
      secondary: '#FFCC80',
      accent: '#4DD0E1',
      surface: '#100E08',
      surface_container_high: '#221C12',
      surface_container_highest: '#322818',
      on_surface: '#FFF8E1',
      outline: '#8A7555',
      live: '#FF9800',
      live_bg: 'rgba(255, 152, 0, 0.2)',
    },
    gradient: ['#100E08', '#3D2A10', '#FFB74D'],
  },
  cultura: {
    slug: 'cultura',
    name: 'Cultura',
    tagline: 'Arte que nos une',
    icon: 'color-palette-outline',
    colors: {
      primary: '#F48FB1',
      primary_container: '#5C2A3D',
      on_primary: '#1F0A14',
      secondary: '#F8BBD9',
      accent: '#7E57C2',
      surface: '#100A0E',
      surface_container_high: '#22141C',
      surface_container_highest: '#321E28',
      on_surface: '#FCE4EC',
      outline: '#8A6070',
      live: '#EC407A',
      live_bg: 'rgba(236, 64, 122, 0.18)',
    },
    gradient: ['#100A0E', '#3D1A30', '#F48FB1'],
  },
  medio_ambiente: {
    slug: 'medio_ambiente',
    name: 'Medio ambiente',
    tagline: 'Planeta en comunidad',
    icon: 'leaf-outline',
    colors: {
      primary: '#81C784',
      primary_container: '#2E5C32',
      on_primary: '#0A1A0C',
      secondary: '#A5D6A7',
      accent: '#4DD0E1',
      surface: '#0A100C',
      surface_container_high: '#142018',
      surface_container_highest: '#1E3024',
      on_surface: '#E8F5E9',
      outline: '#5A8060',
      live: '#66BB6A',
      live_bg: 'rgba(102, 187, 106, 0.2)',
    },
    gradient: ['#0A100C', '#1A4028', '#81C784'],
  },
};

export const DEFAULT_COMMUNITY = 'quedada';

export function getCommunityTheme(slug) {
  const key = slug?.toLowerCase?.().replace(/\s+/g, '_') || DEFAULT_COMMUNITY;
  const normalized = key === 'medio ambiente' ? 'medio_ambiente' : key;
  return COMMUNITY_THEMES[normalized] || COMMUNITY_THEMES[DEFAULT_COMMUNITY];
}

export function mergeThemeWithCommunity(baseColors, communitySlug) {
  const community = getCommunityTheme(communitySlug);
  return { ...baseColors, ...community.colors };
}
