/**
 * EventUs — identidad visual 360° por tipo de comunidad.
 * Cada arquetipo define paleta, tipografía, iconografía y tono narrativo.
 */
const COMMUNITY_THEMES = [
  {
    slug: 'voluntariado',
    name: 'Voluntariado',
    tagline: 'Manos que construyen impacto',
    description: 'Causas locales, brigadas y jornadas de servicio comunitario.',
    icon: 'hand-left-outline',
    mood: ['solidario', 'activo', 'terrenal'],
    theme: {
      primary: '#6BCB77',
      primary_container: '#2D5A3D',
      on_primary: '#0A1F12',
      secondary: '#A8E6CF',
      accent: '#FFD93D',
      surface: '#0D1410',
      surface_container_high: '#1A2B1F',
      surface_container_highest: '#243528',
      on_surface: '#E8F5E9',
      outline: '#5A7A62',
      live: '#6BCB77',
      live_bg: 'rgba(107, 203, 119, 0.18)',
      gradient: ['#0D1410', '#1A3D28', '#6BCB77'],
      pattern: 'leaves',
      fontAccent: 'Manrope',
    },
    matchmaking: { minGroupSize: 3, maxGroupSize: 12, affinityTags: ['causa', 'horario', 'zona'] },
    badges: ['primera_brigada', 'voluntario_constante', 'lider_campo'],
  },
  {
    slug: 'benefico',
    name: 'Benéfico',
    tagline: 'Cada gesto suma',
    description: 'Recaudaciones, donaciones y eventos con causa social clara.',
    icon: 'heart-outline',
    mood: ['cálido', 'esperanzador', 'humano'],
    theme: {
      primary: '#FF8A80',
      primary_container: '#5C2E2A',
      on_primary: '#2A0F0D',
      secondary: '#FFCCBC',
      accent: '#FFD54F',
      surface: '#140E0D',
      surface_container_high: '#2A1A18',
      surface_container_highest: '#3D2622',
      on_surface: '#FFF3F0',
      outline: '#8A6A65',
      live: '#FF5252',
      live_bg: 'rgba(255, 82, 82, 0.15)',
      gradient: ['#140E0D', '#3D1F1A', '#FF8A80'],
      pattern: 'hearts',
      fontAccent: 'Manrope',
    },
    matchmaking: { minGroupSize: 2, maxGroupSize: 8, affinityTags: ['causa', 'donación', 'acompañamiento'] },
    badges: ['donante_oro', 'embajador_causa', 'meta_superada'],
  },
  {
    slug: 'quedada',
    name: 'Quedada',
    tagline: 'Nunca vayas solo',
    description: 'Encuentros informales, hobbies y grupos de afinidad cercanos.',
    icon: 'people-outline',
    mood: ['cercano', 'divertido', 'espontáneo'],
    theme: {
      primary: '#FF6B6B',
      primary_container: '#4A2525',
      on_primary: '#1F0A0A',
      secondary: '#FFB4A2',
      accent: '#4ECDC4',
      surface: '#120C0C',
      surface_container_high: '#221818',
      surface_container_highest: '#322424',
      on_surface: '#FFF0EE',
      outline: '#8A6560',
      live: '#FF6B6B',
      live_bg: 'rgba(255, 107, 107, 0.2)',
      gradient: ['#120C0C', '#3D2020', '#FF6B6B'],
      pattern: 'dots',
      fontAccent: 'Manrope',
    },
    matchmaking: { minGroupSize: 2, maxGroupSize: 6, affinityTags: ['interés', 'edad', 'barrio'] },
    badges: ['anfitrion_quedada', 'conector_social', 'grupo_fiel'],
  },
  {
    slug: 'reunion',
    name: 'Reunión',
    tagline: 'Encuentros con propósito',
    description: 'Mesas de trabajo, asambleas vecinales y coordinación ciudadana.',
    icon: 'briefcase-outline',
    mood: ['serio', 'colaborativo', 'cívico'],
    theme: {
      primary: '#64B5F6',
      primary_container: '#1E3A5F',
      on_primary: '#0A1520',
      secondary: '#90CAF9',
      accent: '#81C784',
      surface: '#0A0E14',
      surface_container_high: '#141C28',
      surface_container_highest: '#1E2A3D',
      on_surface: '#E3F2FD',
      outline: '#5A7088',
      live: '#42A5F5',
      live_bg: 'rgba(66, 165, 245, 0.18)',
      gradient: ['#0A0E14', '#1E3A5F', '#64B5F6'],
      pattern: 'grid',
      fontAccent: 'Manrope',
    },
    matchmaking: { minGroupSize: 4, maxGroupSize: 15, affinityTags: ['tema', 'rol', 'experiencia'] },
    badges: ['facilitador', 'voz_vecinal', 'acuerdo_logrado'],
  },
  {
    slug: 'concierto',
    name: 'Concierto',
    tagline: 'Vive la música juntos',
    description: 'Shows, festivales y experiencias culturales en vivo.',
    icon: 'musical-notes-outline',
    mood: ['eléctrico', 'nocturno', 'festivo'],
    theme: {
      primary: '#CE93D8',
      primary_container: '#4A2C5C',
      on_primary: '#1A0A22',
      secondary: '#E1BEE7',
      accent: '#FF4081',
      surface: '#0C0810',
      surface_container_high: '#1A1224',
      surface_container_highest: '#2A1C38',
      on_surface: '#F3E5F5',
      outline: '#7A6088',
      live: '#E040FB',
      live_bg: 'rgba(224, 64, 251, 0.2)',
      gradient: ['#0C0810', '#2A1040', '#CE93D8'],
      pattern: 'waves',
      fontAccent: 'Manrope',
    },
    matchmaking: { minGroupSize: 2, maxGroupSize: 8, affinityTags: ['género', 'zona', 'transporte'] },
    badges: ['superfan', 'crew_nocturno', 'primera_fila'],
  },
  {
    slug: 'deporte',
    name: 'Deporte',
    tagline: 'Muévete en comunidad',
    description: 'Partidos, entrenamientos grupales y retos físicos locales.',
    icon: 'football-outline',
    mood: ['dinámico', 'competitivo', 'saludable'],
    theme: {
      primary: '#FFB74D',
      primary_container: '#5C3D1A',
      on_primary: '#1F1408',
      secondary: '#FFCC80',
      accent: '#4DD0E1',
      surface: '#100E08',
      surface_container_high: '#221C12',
      surface_container_highest: '#322818',
      on_surface: '#FFF8E1',
      outline: '#8A7555',
      live: '#FF9800',
      live_bg: 'rgba(255, 152, 0, 0.2)',
      gradient: ['#100E08', '#3D2A10', '#FFB74D'],
      pattern: 'stripes',
      fontAccent: 'Manrope',
    },
    matchmaking: { minGroupSize: 4, maxGroupSize: 22, affinityTags: ['nivel', 'posición', 'horario'] },
    badges: ['mvp_comunidad', 'racha_activa', 'organizador_liga'],
  },
  {
    slug: 'cultura',
    name: 'Cultura',
    tagline: 'Arte que nos une',
    description: 'Exposiciones, talleres creativos y patrimonio local.',
    icon: 'color-palette-outline',
    mood: ['expresivo', 'inspirador', 'diverso'],
    theme: {
      primary: '#F48FB1',
      primary_container: '#5C2A3D',
      on_primary: '#1F0A14',
      secondary: '#F8BBD9',
      accent: '#7E57C2',
      surface: '#100A0E',
      surface_container_high: '#22141C',
      surface_container_highest: '#321E28',
      on_surface: '#FCE4EC',
      outline: '#8A6070',
      live: '#EC407A',
      live_bg: 'rgba(236, 64, 122, 0.18)',
      gradient: ['#100A0E', '#3D1A30', '#F48FB1'],
      pattern: 'brush',
      fontAccent: 'Manrope',
    },
    matchmaking: { minGroupSize: 2, maxGroupSize: 10, affinityTags: ['disciplina', 'idioma', 'accesibilidad'] },
    badges: ['curador_local', 'artista_comunitario', 'taller_completado'],
  },
  {
    slug: 'medio_ambiente',
    name: 'Medio ambiente',
    tagline: 'Planeta en comunidad',
    description: 'Limpiezas, reforestación y acción climática de barrio.',
    icon: 'leaf-outline',
    mood: ['consciente', 'renovador', 'natural'],
    theme: {
      primary: '#81C784',
      primary_container: '#2E5C32',
      on_primary: '#0A1A0C',
      secondary: '#A5D6A7',
      accent: '#4DD0E1',
      surface: '#0A100C',
      surface_container_high: '#142018',
      surface_container_highest: '#1E3024',
      on_surface: '#E8F5E9',
      outline: '#5A8060',
      live: '#66BB6A',
      live_bg: 'rgba(102, 187, 106, 0.2)',
      gradient: ['#0A100C', '#1A4028', '#81C784'],
      pattern: 'eco',
      fontAccent: 'Manrope',
    },
    matchmaking: { minGroupSize: 5, maxGroupSize: 30, affinityTags: ['zona', 'herramientas', 'experiencia'] },
    badges: ['guardian_verde', 'hectarea_salvada', 'cero_residuos'],
  },
];

// criteria: evaluada por services/badgeService.js contra user.metrics.
// Las insignias sin criteria (custom) se otorgan por acciones puntuales.
const BADGE_CATALOG = [
  { slug: 'primera_brigada', name: 'Primera brigada', description: 'Tu primer voluntariado confirmado', icon: 'ribbon-outline', tier: 'bronze', points: 10, criteria: { type: 'events_attended', threshold: 1 } },
  { slug: 'voluntario_constante', name: 'Voluntario constante', description: '5 eventos de impacto social', icon: 'repeat-outline', tier: 'silver', points: 50, criteria: { type: 'events_attended', threshold: 5 } },
  { slug: 'lider_campo', name: 'Líder de campo', description: 'Organizaste 3 iniciativas con +20 asistentes', icon: 'flag-outline', tier: 'gold', points: 120, criteria: { type: 'events_created', threshold: 3 } },
  { slug: 'donante_oro', name: 'Donante oro', description: 'Apoyaste 3 causas benéficas', icon: 'heart-outline', tier: 'gold', points: 80, criteria: { type: 'custom', threshold: 3 } },
  { slug: 'embajador_causa', name: 'Embajador de causa', description: 'Invitaste a 5 personas vía enlace', icon: 'share-social-outline', tier: 'silver', points: 40, criteria: { type: 'invites', threshold: 5 } },
  { slug: 'meta_superada', name: 'Meta superada', description: 'Evento benéfico alcanzó el 100% de cupo', icon: 'trophy-outline', tier: 'platinum', points: 150, criteria: { type: 'custom', threshold: 1 } },
  { slug: 'anfitrion_quedada', name: 'Anfitrión de quedada', description: 'Publicaste tu primera quedada', icon: 'home-outline', tier: 'bronze', points: 15, criteria: { type: 'custom', threshold: 1 } },
  { slug: 'conector_social', name: 'Conector social', description: 'Formaste 3 grupos por matchmaking', icon: 'git-network-outline', tier: 'silver', points: 45, criteria: { type: 'custom', threshold: 3 } },
  { slug: 'grupo_fiel', name: 'Grupo fiel', description: 'Mismo grupo asistió a 4 eventos', icon: 'people-circle-outline', tier: 'gold', points: 90, criteria: { type: 'custom', threshold: 4 } },
  { slug: 'facilitador', name: 'Facilitador', description: 'Moderaste un muro de evento activo', icon: 'chatbubbles-outline', tier: 'silver', points: 35, criteria: { type: 'custom', threshold: 1 } },
  { slug: 'voz_vecinal', name: 'Voz vecinal', description: '10 aportes en muros de comunidad', icon: 'megaphone-outline', tier: 'gold', points: 70, criteria: { type: 'wall_posts', threshold: 10 } },
  { slug: 'superfan', name: 'Superfan', description: 'Asististe a 3 conciertos en un mes', icon: 'star-outline', tier: 'silver', points: 55, criteria: { type: 'custom', threshold: 3 } },
  { slug: 'guardian_verde', name: 'Guardián verde', description: '3 acciones ambientales completadas', icon: 'leaf-outline', tier: 'gold', points: 85, criteria: { type: 'custom', threshold: 3 } },
  { slug: 'radar_activo', name: 'Radar activo', description: 'Descubriste 10 eventos con geolocalización', icon: 'locate-outline', tier: 'bronze', points: 20, criteria: { type: 'custom', threshold: 10 } },
  { slug: 'entrada_verificada', name: 'Entrada verificada', description: 'Check-in con QR dinámico sin fraude', icon: 'shield-checkmark-outline', tier: 'silver', points: 25, criteria: { type: 'check_ins', threshold: 1 } },
  { slug: 'creador_impacto', name: 'Creador de impacto', description: 'Publicaste 5 iniciativas en modo creador', icon: 'create-outline', tier: 'platinum', points: 200, criteria: { type: 'events_created', threshold: 5 } },
  { slug: 'album_colaborador', name: 'Álbum colaborador', description: 'Subiste fotos a 3 álbumes post-evento', icon: 'images-outline', tier: 'silver', points: 30, criteria: { type: 'custom', threshold: 3 } },
  { slug: 'organizador_metricas', name: 'Organizador data-driven', description: 'Consultaste panel de métricas 10 veces', icon: 'stats-chart-outline', tier: 'gold', points: 60, criteria: { type: 'custom', threshold: 10 } },
];

module.exports = { COMMUNITY_THEMES, BADGE_CATALOG };
